version: '3'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=spring
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3360:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-data/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
